[features]
seeds = false
skip-lint = false
[programs.localnet]
ask_network = "EarWDrZeaMyMRuiWXVuFH2XKJ96Mg6W6h9rv51BCHgRD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/op/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
