[features]
seeds = false
skip-lint = false

[programs.devnet]
ask_network = "8WfQ3nACPcoBKxFnN4ekiHp8bRTd35R4L8Pu3Ak15is3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/root/.config/solana/asknetwork-deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
