[features]
seeds = false
skip-lint = false

[programs.localnet]
ask_network = "AKVXMk2HpyozBHvMc66jDNRdKMbq2oCzdWBNx64mZsc1"

[programs.devnet]
ask_network = "wvQ95noxaE62kWjsMmsNRpUXmHoHVwcPxhtes1rnA8V"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/root/.config/solana/asknetwork-deploy.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
